---
name: PSMCore
author:  Ad5001
version: 1.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8]
main: Ad5001\PSMCore\Main
commands:
 psmcoreactplugin:
  usage: Internal 
  permission: psmcore.internal
  description: Internal command.
permissions:
 psmcore.internal:
  default: op
...